cloud:
  aws:
    region:
      static: us-west-2
    stack:
      auto: false

servicebroker:
  terraformToken: # SET THIS
  terraformOrganization: # SET THIS
  terraformVersion: 0.11.1
  webhookUrl: # SET THIS
  vcsRepo: niallthomson/tf-test
  oauthTokenId: # SET THIS
  env:
    AWS_ACCESS_KEY_ID: asdasd
    AWS_SECRET_ACCESS_KEY: asdasd
    AWS_DEFAULT_REGION: us-west-2