servicebroker:
  auth:
    username: someuser
    password: somethingsecure
  terraformToken: # SET THIS
  terraformOrganization: # SET THIS
  terraformVersion: 0.11.1
  webhookUrl: # SET THIS
  vcsRepo: niallthomson/tf-test
  oauthTokenId: # SET THIS
  env:
    AWS_ACCESS_KEY_ID: # SET THIS
    AWS_SECRET_ACCESS_KEY: # SET THIS
    AWS_DEFAULT_REGION: us-west-2