servicebroker:
  auth:
    username: someuser
    password: somethingsecure
  terraform:
    token: # SET THIS
    organization: # SET THIS
    oauth-token-id: # SET THIS
    version: 0.11.1
  webhook-url: # SET THIS
  vcs-repo: niallthomson/tf-test
  env:
    AWS_ACCESS_KEY_ID: # SET THIS
    AWS_SECRET_ACCESS_KEY: # SET THIS
    AWS_DEFAULT_REGION: us-west-2