servicebroker:
  auth:
    username: someuser
    password: somethingsecure
  terraform:
    token: # SET THIS
    organization: # SET THIS
    oauth-token-id: # SET THIS
    version: 0.11.14
  webhook-url: # SET THIS
  vcs-repo: niallthomson/tf-test
  context:
      awsAccessKeyId: # SET THIS
      awsSecretAccessKey: # SET THIS
      awsRegion: us-west-2
      googleRegion: us-central1
      googleZone: us-central1-a
      googleProject: # SET THIS
      googleCredentials: # SET THIS
      vaultAddr: # SET THIS
      vaultToken: # SET THIS